
quarkus.hibernate-orm.generation=update
quarkus.hibernate-orm.log.sql=true

%postgres.quarkus.datasource.db-kind=postgresql
%postgres.quarkus.datasource.username=admin
%postgres.quarkus.datasource.password=admin
%postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

quarkus.jacoco.excludes=it/exprivia/dto/**, it/exprivia/models/**, it/exprivia/repository/**, it/exprivia/mapper/**, it/exprivia, it/exprivia/exception/**, it/exprivia/controller/**


