#dev mode
quarkus.hibernate-orm.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

#profilo postgres
%postgres.quarkus.datasource.db-kind=postgresql
%postgres.quarkus.datasource.username=admin
%postgres.quarkus.datasource.password=admin
%postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
%postgres.quarkus.hibernate-orm.generation=update
