it.proxy.TvSeriesProxy/mp-rest/url=https://api.tvmaze.com
it.proxy.TvSeriesProxy/mp-rest/scope=jakarta.inject.Singleton

# Timeout per evitare di bloccare l'health check

it.proxy.TvSeriesProxy/mp-rest/connectTimeout=1000
it.proxy.TvSeriesProxy/mp-rest/readTimeout=1000

it.proxy.EpisodeProxy/mp-rest/url=https://api.tvmaze.com

default.title = "stranger things"

